module.exports = {
  apps: [
    {
      name: 'shiesty-server',
      script: './server/server.js',
      cwd: '/home/ubuntu/shiesty-raiders',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'development',
        PORT: 3000,
      },
      watch: true,
      watch_delay: 1000,
      ignore_watch: [
        'node_modules',
        'client',
        'logs',
        '.git',
        '.windsurf',
        '*.log',
        'tools',
        'docs',
        '*md*',
        '*txt*',
      ],
      watch_options: {
        followSymlinks: false,
        usePolling: true,
        interval: 1000,
      },
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: '10s',
      kill_timeout: 5000,
      log_file: './logs/combined.log',
      out_file: './logs/out.log',
      error_file: './logs/error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
    },
  ],
};
